In [1]:
# ==================================================
# Student Productivity Analytics Project
# Data Cleaning Notebook
# ==================================================

# Goal:
# Clean and preprocess the raw dataset
# for analysis and machine learning.

In [2]:
# ==================================================
# Import Libraries
# ==================================================

import pandas as pd
import numpy as np
import os

In [3]:
# ==================================================
# Connect Google Drive
# ==================================================

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
# ==================================================
# Project Paths
# ==================================================

PROJECT_PATH = "/content/drive/MyDrive/student-productivity-analytics"

RAW_DATA_PATH = f"{PROJECT_PATH}/data/raw"

CLEANED_DATA_PATH = f"{PROJECT_PATH}/data/cleaned"

os.makedirs(CLEANED_DATA_PATH, exist_ok=True)

print("Paths Ready!")

Paths Ready!

In [6]:
# ==================================================
# Load Raw Dataset
# ==================================================

dataset_path = f"{RAW_DATA_PATH}/student_productivity_dataset.csv"

df = pd.read_csv(dataset_path)

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [7]:
# ==================================================
# Preview Dataset
# ==================================================

df.head()
df.shape
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             15000 non-null  int64
 1   Date                   15000 non-null  object
 2   Persona                15000 non-null  object
 3   Age                    15000 non-null  int64
 4   Gender                 15000 non-null  object
 5   Department             15000 non-null  object
 6   Year_of_Study          15000 non-null  int64
 7   Sleep_Hours            15000 non-null  float64
 8   Study_Hours            15000 non-null  float64
 9   Screen_Time_Hours      15000 non-null  float64
 10  Stress_Level           15000 non-null  float64
 11  Focus_Score            15000 non-null  float64
 12  Mood_Score             15000 non-null  float64
 13  Attendance_Percentage  15000 non-null  float64
 14  Assignment_Completion  15000 non-null  float64
 15  Productivity_Score     15000 non-null  float64
 16  Exam_Score             15000 non-null  float64
 17  Burnout_Risk           15000 non-null  object
dtypes: float64(10), int64(3), object(5)
memory usage: 2.1+ MB

Student_ID               0
Date                     0
Persona                  0
Age                      0
Gender                   0
Department               0
Year_of_Study            0
Sleep_Hours              0
Study_Hours              0
Screen_Time_Hours        0
Stress_Level             0
Focus_Score              0
Mood_Score               0
Attendance_Percentage    0
Assignment_Completion    0
Productivity_Score       0
Exam_Score               0
Burnout_Risk             0
dtype: int64

In [8]:
# ==================================================
# Introduce Missing Values
# ==================================================

for col in [
    "Sleep_Hours",
    "Study_Hours",
    "Mood_Score"
]:
    df.loc[
        df.sample(frac=0.02).index,
        col
    ] = np.nan

print("Missing Values Introduced!")

Missing Values Introduced!

In [9]:
# ==================================================
# Missing Values After Injection
# ==================================================

df.isnull().sum()

Student_ID                 0
Date                       0
Persona                    0
Age                        0
Gender                     0
Department                 0
Year_of_Study              0
Sleep_Hours              300
Study_Hours              300
Screen_Time_Hours          0
Stress_Level               0
Focus_Score                0
Mood_Score               300
Attendance_Percentage      0
Assignment_Completion      0
Productivity_Score         0
Exam_Score                 0
Burnout_Risk               0
dtype: int64

In [10]:
# ==================================================
# Handle Missing Values
# ==================================================

df["Sleep_Hours"].fillna(
    df["Sleep_Hours"].median(),
    inplace=True
)

df["Study_Hours"].fillna(
    df["Study_Hours"].median(),
    inplace=True
)

df["Mood_Score"].fillna(
    df["Mood_Score"].median(),
    inplace=True
)

print("Missing Values Handled!")

Missing Values Handled!

/tmp/ipykernel_16819/1557492484.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Sleep_Hours"].fillna(
/tmp/ipykernel_16819/1557492484.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Study_Hours"].fillna(
/tmp/ipykernel_16819/1557492484.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Mood_Score"].fillna(

In [11]:
# ==================================================
# Duplicate Check
# ==================================================

df.duplicated().sum()

np.int64(0)

In [12]:
# ==================================================
# Duplicate Check
# ==================================================

df.duplicated().sum()

np.int64(0)

In [13]:
# ==================================================
# Outlier Inspection
# ==================================================

df[
    (df["Study_Hours"] > 12)
]

,Student_ID,Date,Persona,Age,Gender,Department,Year_of_Study,Sleep_Hours,Study_Hours,Screen_Time_Hours,Stress_Level,Focus_Score,Mood_Score,Attendance_Percentage,Assignment_Completion,Productivity_Score,Exam_Score,Burnout_Risk
256,9,2025-01-17,Inconsistent,19,Female,Computer Science,3,9.5,13.3,8.8,5.6,6.1,6.8,100.0,100.0,66.5,91.4,Low
280,10,2025-01-11,Inconsistent,23,Male,Computer Science,1,5.9,13.0,8.1,5.4,6.8,6.0,85.0,100.0,67.4,89.8,Low
541,19,2025-01-02,Burnout,22,Female,Business,4,4.0,12.6,8.4,7.8,5.2,3.4,43.7,100.0,50.1,63.6,Medium
4279,143,2025-01-20,Inconsistent,18,Male,Information Technology,3,5.9,12.2,10.3,5.6,3.4,1.0,69.8,100.0,41.1,73.0,Low
4443,149,2025-01-04,Burnout,18,Female,Mechanical,4,4.2,12.1,7.8,10.0,6.0,4.2,47.2,100.0,48.5,59.7,High
4565,153,2025-01-06,Burnout,19,Male,Information Technology,3,4.9,12.5,8.6,8.9,6.4,2.1,65.8,100.0,49.6,73.9,High
5009,167,2025-01-30,Burnout,22,Male,Electronics,4,5.4,12.4,9.5,8.8,5.3,2.9,64.9,100.0,46.7,71.7,Medium
5754,192,2025-01-25,Burnout,25,Female,Mechanical,3,4.7,12.1,7.6,10.0,4.2,5.6,43.8,100.0,44.3,53.3,High
6951,232,2025-01-22,Inconsistent,23,Female,Business,3,6.3,12.2,6.8,7.4,4.6,5.7,69.0,100.0,51.6,69.4,Medium
6959,232,2025-01-30,Inconsistent,23,Female,Business,3,3.5,12.5,10.1,4.8,5.2,6.5,58.1,100.0,61.4,79.9,Low
7471,250,2025-01-02,Inconsistent,18,Male,Electronics,4,4.2,13.5,3.8,6.0,6.0,5.7,62.1,100.0,63.8,84.8,Low
7699,257,2025-01-20,Burnout,24,Male,Business,3,5.4,12.5,7.5,8.8,4.9,4.1,53.3,100.0,47.9,58.9,Medium
9036,302,2025-01-07,Burnout,20,Female,Computer Science,3,6.0,12.2,6.9,9.1,3.8,3.6,65.0,100.0,40.8,71.6,Medium
9957,332,2025-01-28,Burnout,22,Female,Information Technology,1,5.3,12.4,5.9,9.3,4.3,4.9,55.7,100.0,45.9,71.5,Medium
10227,341,2025-01-28,Inconsistent,23,Male,Business,2,7.0,14.0,10.0,3.6,6.2,4.8,93.6,100.0,69.1,95.5,Low
10801,361,2025-01-02,Burnout,21,Female,Computer Science,1,4.9,12.6,7.8,8.9,4.8,4.4,46.5,100.0,48.2,65.2,High
12698,424,2025-01-09,Inconsistent,20,Male,Computer Science,1,4.4,12.6,7.7,7.6,7.0,5.4,67.0,100.0,61.4,77.8,Medium
12813,428,2025-01-04,Inconsistent,18,Male,Information Technology,1,6.1,14.0,11.0,10.0,3.5,9.9,58.0,98.3,56.0,60.3,Medium
13130,438,2025-01-21,Burnout,25,Male,Business,4,5.3,12.6,6.1,8.6,3.8,5.0,53.7,96.8,45.8,61.7,Medium
13321,445,2025-01-02,Inconsistent,21,Female,Information Technology,3,5.9,14.0,4.4,9.3,3.5,7.1,50.4,100.0,51.5,70.4,Medium
13961,466,2025-01-12,Inconsistent,25,Male,Computer Science,2,4.9,12.4,12.7,6.1,7.7,3.7,76.1,100.0,63.1,91.7,Medium
14273,476,2025-01-24,Burnout,23,Female,Mechanical,2,4.8,12.2,6.1,9.4,6.5,6.2,62.8,100.0,56.1,76.9,High
14750,492,2025-01-21,Inconsistent,24,Female,Mechanical,3,9.9,12.5,7.7,3.7,1.9,6.5,100.0,91.6,50.9,87.8,Low
14947,499,2025-01-08,Burnout,22,Male,Electronics,2,4.6,13.6,7.0,9.8,6.1,2.6,67.1,100.0,50.7,76.4,High

In [14]:
# ==================================================
# Feature Engineering
# ==================================================

df["Study_Efficiency"] = (
    df["Exam_Score"] /
    (df["Study_Hours"] + 1)
)

print("Feature Created!")

Feature Created!

In [15]:
# ==================================================
# Wellness Score
# ==================================================

df["Wellness_Score"] = (
    df["Sleep_Hours"] * 0.4
    + df["Mood_Score"] * 0.3
    - df["Stress_Level"] * 0.3
)

print("Wellness Score Added!")

Wellness Score Added!

In [16]:
# ==================================================
# Date Conversion
# ==================================================

df["Date"] = pd.to_datetime(df["Date"])

print("Date Converted!")

Date Converted!

In [17]:
# ==================================================
# Final Validation
# ==================================================

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             15000 non-null  int64
 1   Date                   15000 non-null  datetime64[ns]
 2   Persona                15000 non-null  object
 3   Age                    15000 non-null  int64
 4   Gender                 15000 non-null  object
 5   Department             15000 non-null  object
 6   Year_of_Study          15000 non-null  int64
 7   Sleep_Hours            15000 non-null  float64
 8   Study_Hours            15000 non-null  float64
 9   Screen_Time_Hours      15000 non-null  float64
 10  Stress_Level           15000 non-null  float64
 11  Focus_Score            15000 non-null  float64
 12  Mood_Score             15000 non-null  float64
 13  Attendance_Percentage  15000 non-null  float64
 14  Assignment_Completion  15000 non-null  float64
 15  Productivity_Score     15000 non-null  float64
 16  Exam_Score             15000 non-null  float64
 17  Burnout_Risk           15000 non-null  object
 18  Study_Efficiency       15000 non-null  float64
 19  Wellness_Score         15000 non-null  float64
dtypes: datetime64[ns](1), float64(12), int64(3), object(4)
memory usage: 2.3+ MB

In [18]:
# ==================================================
# Final Dataset Preview
# ==================================================

df.head()

,Student_ID,Date,Persona,Age,Gender,Department,Year_of_Study,Sleep_Hours,Study_Hours,Screen_Time_Hours,Stress_Level,Focus_Score,Mood_Score,Attendance_Percentage,Assignment_Completion,Productivity_Score,Exam_Score,Burnout_Risk,Study_Efficiency,Wellness_Score
0,1,2025-01-01,High Performer,18,Female,Information Technology,2,7.9,5.4,4.6,5.5,7.8,7.8,100.0,99.8,51.6,65.0,Low,10.156250,3.85
1,1,2025-01-02,High Performer,18,Female,Information Technology,2,7.9,5.0,3.5,4.2,6.1,6.3,96.2,89.2,43.5,49.9,Low,8.316667,3.79
2,1,2025-01-03,High Performer,18,Female,Information Technology,2,6.8,4.1,5.5,3.8,8.1,6.6,100.0,89.6,50.1,52.2,Low,10.235294,3.56
3,1,2025-01-04,High Performer,18,Female,Information Technology,2,7.8,4.9,3.7,3.4,9.9,8.0,100.0,100.0,63.3,64.0,Low,10.847458,4.50
4,1,2025-01-05,High Performer,18,Female,Information Technology,2,7.7,3.5,2.7,4.2,8.7,8.2,100.0,90.3,53.5,54.8,Low,12.177778,4.28

In [19]:
# ==================================================
# Save Cleaned Dataset
# ==================================================

cleaned_path = (
    f"{CLEANED_DATA_PATH}/"
    "student_productivity_cleaned.csv"
)

df.to_csv(cleaned_path, index=False)

print("Cleaned Dataset Saved!")

Cleaned Dataset Saved!

In [20]:
# ==================================================
# Verify Cleaned Files
# ==================================================

os.listdir(CLEANED_DATA_PATH)

['student_productivity_cleaned.csv']